sm8550-common: Add missing libhidltcmd & motorola.hardware.tcmd@1.0
error: vendor/motorola/sm8550-common/Android.bp:16646:1: motorola.hardware.tcmd@1.0-service depends on undefined module libhidltcmd.
Or did you mean [libhidl libhidl-gen libhidl_test libhidlbase libidlcli]?
error: vendor/motorola/sm8550-common/Android.bp:16646:1: motorola.hardware.tcmd@1.0-service depends on undefined module motorola.hardware.tcmd@1.0.
Or did you mean [com.motorola.motosignature]?
fatal errors encountered

Change-Id: I4cc25c0e15e36511408aee3d4f9c08482f26c0a3