sm8550-common: Patch libwfdservice to resolve duplicate dependencies
Fixes:
error: module libwfdservice variant
android_arm_armv8-a_cortex-a76_static: depends on multiple
versions of the same aidl_interface:
android.media.audio.common.types-V2-cpp-source,
android.media.audio.common.types-V3-cpp-source

Change-Id: Ifa975bf8d8f971e7d2b000b40898e870aebd2ab2